language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - coverage=false
    - CODECOV_TOKEN="062645b0-9868-4c0b-a18e-f80e4cc5fcc4"

sudo: false


install:
  - composer update --prefer-dist --no-interaction --no-suggest

script:
  - composer unit-test

after_success:
  - if [[ $coverage = 'true' ]]; then bash <(curl -s https://codecov.io/bash); fi

matrix:
  include:

    - php: 7.1.3

    - php: 7.2
      env: coverage=true

    - php: 7.3

