language: php

cache:
  directories:
    - $HOME/.composer/cache


sudo: false


install:
  - composer update --prefer-dist --no-interaction --no-suggest

script:
  - composer unit-test

#after_success:
#  - if [[ $coverage = 'true' ]]; then bash <(curl -s https://codecov.io/bash); fi

matrix:
  include:

    - php: 7.1.3

    - php: 7.2


    - php: 7.3

    - php: nightly

  allow_failures:
    - php: nightly
